# Generated by Django 3.2.5 on 2021-07-22 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiretuber', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiretuber',
            old_name='tuber_id',
            new_name='tubers_id',
        ),
    ]
