# Generated by Django 3.2.4 on 2021-06-26 08:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('code', 'code'), ('mobile', 'mobile'), ('vlog', 'vlog'), ('comedy', 'comedy'), ('gaming', 'gaming'), ('film_making', 'film_making'), ('cooking', 'cooking')], max_length=225),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='cemera_type',
            field=models.CharField(choices=[('cannon', 'cannon'), ('nikon', 'nikon'), ('sony', 'sony'), ('red', 'red'), ('fuji', 'fuji'), ('panasonic', 'panasonic'), ('other', 'other')], max_length=225),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small', 'small'), ('large', 'large')], max_length=225),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='discriptiom',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
