# Generated by Django 3.2.4 on 2021-07-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20210626_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtuber',
            old_name='discriptiom',
            new_name='discription',
        ),
    ]
