# Generated by Django 3.2.4 on 2021-06-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='button_text',
            field=models.EmailField(max_length=225),
        ),
    ]
