# Generated by Django 3.2.4 on 2021-06-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='insta_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
