# Generated by Django 3.2.4 on 2021-06-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_alter_team_insta_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='yt_link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='insta_link',
            field=models.CharField(max_length=255),
        ),
    ]
