# Generated by Django 3.2.4 on 2021-07-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_auto_20210624_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='button_text',
            field=models.CharField(max_length=225),
        ),
    ]
